#!/usr/bin/env sh

# variables
config=$HOME/.config/hypr/themes/minimal
scripts=$config/scripts

$config/waybar/waybar.sh
# $scripts/waybar/tools/dynamic &

# wallpaper
# TODO: create random wallpaper script